CI: run test suite in full build jobs and report results as JUnit
The mini build lacks the optional test dependencies (usb, avahi, libcurl, ...) so it builds no test programs.
Tests run only on the full build jobs.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -40,6 +40,18 @@ make-dist:
   - tar xzf ../sane-backends-*.tar.gz --strip-components=1
   - (set -x; ./configure $CONFIGURE_OPTS)
   - eval "(set -x; make -w -O -j2 -k $MAKE_FLAGS)"
+  # Run the test suite (gated on RUN_TESTS) and emit a JUnit report.
+  # The report is generated even on failure so results render in the
+  # Tests tab.
+  - |
+    if test "$RUN_TESTS" = "yes"; then
+      (set -x; make -w -O -j2 check) || rc=$?
+      ../tools/junit-from-trs.sh . > junit_report.xml
+      exit ${rc:-0}
+    fi
+  artifacts:
+    reports:
+      junit: build/junit_report.xml
 
 debian-11-mini:
   image: $REGISTRY_HUB:debian-bullseye-mini
@@ -57,6 +69,7 @@ debian-12-full:
   variables:
     CONFIGURE_OPTS: "$CONFIGURE_MINI $CONFIGURE_FULL"
     MAKE_FLAGS: "CFLAGS=-Werror CXXFLAGS=-Werror"
+    RUN_TESTS: "yes"
   <<: *compile_definition
   after_script:
   - make -C build/doc html-pages
@@ -67,6 +80,8 @@ debian-12-full:
     - sane-backends-*.tar.gz
     - lists
     - doc/sanei-html
+    reports:
+      junit: build/junit_report.xml
     expire_in: 1 day
 
 fedora-39-clang:
@@ -74,6 +89,7 @@ fedora-39-clang:
   variables:
     CONFIGURE_OPTS: "$CONFIGURE_MINI $CONFIGURE_FULL"
     MAKE_FLAGS: "CFLAGS='-Werror -Wno-error=unused-but-set-variable' CXXFLAGS='-Werror'"
+    RUN_TESTS: "yes"
   <<: *compile_definition
 
 alpine-3.18-musl:
@@ -81,6 +97,7 @@ alpine-3.18-musl:
   variables:
     CONFIGURE_OPTS: "$CONFIGURE_MINI $CONFIGURE_FULL"
     MAKE_FLAGS: "CFLAGS='-Werror -Wno-pedantic' CXXFLAGS=-Werror"
+    RUN_TESTS: "yes"
   <<: *compile_definition
 
 ubuntu-23.10:
@@ -88,6 +105,7 @@ ubuntu-23.10:
   variables:
     CONFIGURE_OPTS: "$CONFIGURE_MINI $CONFIGURE_FULL"
     MAKE_FLAGS: "CFLAGS=-Werror CXXFLAGS=-Werror"
+    RUN_TESTS: "yes"
   <<: *compile_definition
 
 # This snapshot stage job makes sure that the source tarball has all
